export const tickets = [
  {
    id: 1,
    event: 'Arijit Singh Live Concert',
    venue: 'DY Patil Stadium, Mumbai',
    date: '14 Jun 2025',
    time: '7:00 PM',
    section: 'A1',
    row: '12',
    seat: '08',
    price: 4500,
    status: 'active',
    category: 'Concert',
    purchasedOn: '2025-05-01',
  },
  {
    id: 2,
    event: 'IPL Final 2025 - MI vs CSK',
    venue: 'Wankhede Stadium, Mumbai',
    date: '25 May 2025',
    time: '7:30 PM',
    section: 'G3',
    row: '5',
    seat: '22',
    price: 8000,
    status: 'listed',
    category: 'Sports',
    purchasedOn: '2025-04-20',
  },
  {
    id: 3,
    event: 'Coldplay Music of the Spheres',
    venue: 'Narendra Modi Stadium, Ahmedabad',
    date: '18 Jan 2025',
    time: '6:00 PM',
    section: 'VIP',
    row: '2',
    seat: '15',
    price: 12000,
    status: 'sold',
    category: 'Concert',
    purchasedOn: '2024-12-10',
  },
  {
    id: 4,
    event: 'Sunburn Festival 2025',
    venue: 'Vagator Beach, Goa',
    date: '28 Dec 2025',
    time: '4:00 PM',
    section: 'GA',
    row: 'N/A',
    seat: 'N/A',
    price: 3200,
    status: 'active',
    category: 'Festival',
    purchasedOn: '2025-05-15',
  },
  {
    id: 5,
    event: 'Hamlet - The Play',
    venue: 'NCPA, Mumbai',
    date: '3 Jul 2025',
    time: '6:30 PM',
    section: 'B2',
    row: '7',
    seat: '11',
    price: 2000,
    status: 'pending',
    category: 'Theatre',
    purchasedOn: '2025-05-18',
  },
  {
    id: 6,
    event: 'Pro Kabaddi League Final',
    venue: 'Dome, NSCI SVP Stadium',
    date: '10 Aug 2025',
    time: '8:00 PM',
    section: 'C1',
    row: '9',
    seat: '3',
    price: 1500,
    status: 'active',
    category: 'Sports',
    purchasedOn: '2025-05-10',
  },
];

export const transactions = [
  { id: 'TXN001', event: 'Arijit Singh Live Concert', type: 'Purchase', amount: 4500, date: '01 May 2025', status: 'completed' },
  { id: 'TXN002', event: 'Coldplay Music of the Spheres', type: 'Sale', amount: 18500, date: '15 Apr 2025', status: 'completed' },
  { id: 'TXN003', event: 'IPL Final 2025', type: 'Listed', amount: 12000, date: '20 Apr 2025', status: 'pending' },
  { id: 'TXN004', event: 'Sunburn Festival 2025', type: 'Purchase', amount: 3200, date: '15 May 2025', status: 'completed' },
  { id: 'TXN005', event: 'Hamlet - The Play', type: 'Purchase', amount: 2000, date: '18 May 2025', status: 'processing' },
];

export const statsData = [
  { month: 'Jan', revenue: 12000, spent: 8000 },
  { month: 'Feb', revenue: 8500, spent: 5000 },
  { month: 'Mar', revenue: 15000, spent: 9000 },
  { month: 'Apr', revenue: 18500, spent: 6000 },
  { month: 'May', revenue: 7200, spent: 9700 },
];

export const upcomingEvents = [
  { id: 1, name: 'Arijit Singh Live', date: '14 Jun', daysLeft: 25, category: 'Concert' },
  { id: 2, name: 'IPL Final 2025', date: '25 May', daysLeft: 5, category: 'Sports' },
  { id: 3, name: 'Sunburn Festival', date: '28 Dec', daysLeft: 222, category: 'Festival' },
];
